"""Profiles models."""

# Django
from django.db import models
from django.conf import settings

# Utils
from bookshare.utils import BookShareModel


class Profile(BookShareModel):
    """
    Profile model.
    A profile holds the information about the user like his picture,
    biography and statistics generated by tasks.
    """

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    biography = models.TextField(max_length=500, blank=True)
    picture = models.ImageField(
        'profile picture',
        upload_to='users/picture',
        blank=True,
        null=True
    )

    # Statistics

    lend_offered = models.PositiveSmallIntegerField(default=0)
    lend_taked = models.PositiveSmallIntegerField(default=0)
    reputation = models.FloatField(
        blank=True,
        null=True,
        help_text='User reputation based on the lends taked and offered.'
    )

    def __str__(self):
        """Return str of the user."""
        return str(self.user)
