# Generated by Django 3.1.5 on 2021-02-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime on when the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Datetime on when the object was modified.', verbose_name='modified_at')),
                ('name', models.CharField(max_length=148, verbose_name='circle name')),
                ('slug_name', models.SlugField(max_length=148, unique=True, verbose_name='circle slug name')),
                ('about', models.TextField(max_length=500, verbose_name='circle description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures', verbose_name='circle picture')),
                ('is_verified', models.BooleanField(default=False, help_text='An oficial organization or community.', verbose_name='verified')),
                ('is_public', models.BooleanField(default=True, help_text='Public circles are filter in so anyone can know about it.')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='If members limits is 0, the circle has not limit.', verbose_name='members limits')),
                ('lends_offered', models.PositiveIntegerField(default=0)),
                ('lends_taked', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-lends_taked', '-lends_offered'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime on when the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Datetime on when the object was modified.', verbose_name='modified_at')),
                ('code', models.CharField(max_length=128)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime on when the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Datetime on when the object was modified.', verbose_name='modified_at')),
                ('remaning_invitations', models.PositiveSmallIntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False, verbose_name='circle admin')),
                ('lends_offered', models.PositiveIntegerField(default=0)),
                ('lends_taked', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Only active users are allowed.', verbose_name='active status')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.circle')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
