# Generated by Django 3.1.5 on 2021-02-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.FloatField(blank=True, help_text='User reputation based on the lends taked and offered.', null=True),
        ),
    ]
