# Generated by Django 3.1.5 on 2021-02-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime on when the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Datetime on when the object was modified.', verbose_name='modified_at')),
                ('title', models.CharField(max_length=148, verbose_name='book title')),
                ('author', models.CharField(max_length=148, verbose_name='book author')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/cover', verbose_name='book cover')),
                ('isbn', models.PositiveBigIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime on when the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Datetime on when the object was modified.', verbose_name='modified_at')),
                ('comments', models.TextField(blank=True, max_length=255)),
                ('taked', models.BooleanField(default=False, verbose_name='book taked')),
                ('returned', models.BooleanField(default=False, help_text='If returned is True, the book was returned.', verbose_name='book returned')),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lends.book')),
                ('circle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circles.circle')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
