# Generated by Django 3.1.5 on 2021-02-14 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('success', 'asdasd'), ('info', 'asdasd'), ('warning', 'asdasd'), ('error', 'asdasd')], default='info', max_length=32)),
                ('actor_object_id', models.PositiveIntegerField()),
                ('object_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_actor', to='contenttypes.contenttype')),
                ('object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_object', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_target', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-datetime'],
                'index_together': {('recipient', 'unread')},
            },
        ),
    ]
